# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bestCandidate_RCpp <- function(findIn, p, n, sigma, tolerance, Ftrace, criteria, Y, X1, X0, k) {
    .Call(`_StepReg_bestCandidate_RCpp`, findIn, p, n, sigma, tolerance, Ftrace, criteria, Y, X1, X0, k)
}

