# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimization <- function(findIn, p, n, sigma, tolerance, Ftrace, criteria, Y, X1, X0, k, SST) {
    .Call(`_StepReg_optimization`, findIn, p, n, sigma, tolerance, Ftrace, criteria, Y, X1, X0, k, SST)
}

